% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  10pt,
  letterpaper]{article}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
  \setmainfont[]{Charis SIL}
  \setmonofont[]{Monaco}
  \setmathfont[]{Monaco}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin = 1in]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{tabularx}
\usepackage{threeparttable}
\usepackage{booktabs}
\usepackage{tipa}
\let\Oldtexttt\texttt
\renewcommand\texttt[1]{{\ttfamily\color{BrickRed}#1}}
\usepackage{authoraftertitle}
\usepackage{fancyhdr}
\pagestyle{fancy}
\rfoot{\copyright Matt Hunt Gardner}
\cfoot{\thepage}
\lhead{Doing LVC with \textit{R}: \MyTitle}
\rhead{}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
% Make links footnotes instead of hotlinks:
\DeclareRobustCommand{\href}[2]{#2\footnote{\url{#1}}}
\hypersetup{
  pdftitle={Getting to Know Your Data},
  pdfauthor={Matt Hunt Gardner},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Getting to Know Your Data}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{from
\href{https://lingmethodshub.github.io/content/R/lvc_r/}{Doing LVC with
\emph{R}}}
\author{Matt Hunt Gardner}
\date{2022-12-15}

\begin{document}
\maketitle
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[sharp corners, frame hidden, enhanced, interior hidden, boxrule=0pt, borderline west={3pt}{0pt}{shadecolor}, breakable]}{\end{tcolorbox}}\fi

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}
\hypertarget{getting-to-know-the-t-d-deletion-data}{%
\subsection{Getting to know the (t, d) deletion
data}\label{getting-to-know-the-t-d-deletion-data}}

If you followed the previous section you now have an object in \emph{R}
called \texttt{td}. If not, you can load it now with either of the
following codes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{td }\OtherTok{\textless{}{-}} \FunctionTok{read.delim}\NormalTok{(}\StringTok{"https://www.dropbox.com/s/jxlfuogea3lx2pu/deletiondata.txt?dl=1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{td }\OtherTok{\textless{}{-}} \FunctionTok{read.delim}\NormalTok{(}\StringTok{"Data/deletiondata.txt"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{getting-a-snapshot-of-the-data}{%
\subsubsection{Getting a Snapshot of the
Data}\label{getting-a-snapshot-of-the-data}}

Now that you have some data loaded into \emph{R} you can start exploring
it. At any time you can type \texttt{td} into the console window to see
what that object actually represents. Try it.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{td}
\end{Highlighting}
\end{Shaded}

To find out how many columns there are in your data frame (this is what
\emph{R} calls spreadsheets), use the function \texttt{nrow()}.
Similarly, to find out how many columns are in the data frame, use the
function \texttt{ncol()}. The function \texttt{dim()} gives both.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 6989
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ncol}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 6989   12
\end{verbatim}

There are 6,989 rows and 12 columns in this data frame.

The \texttt{summary()} function is one of the most useful functions
you'll use in \emph{R}. It gives you a quick snapshot of a data frame.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Dep.Var             Stress            Category          Morph.Type       
 Length:6989        Length:6989        Length:6989        Length:6989       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
    Before             After             Speaker               YOB      
 Length:6989        Length:6989        Length:6989        Min.   :1915  
 Class :character   Class :character   Class :character   1st Qu.:1952  
 Mode  :character   Mode  :character   Mode  :character   Median :1965  
                                                          Mean   :1967  
                                                          3rd Qu.:1991  
                                                          Max.   :1999  
     Sex             Education             Job            Phoneme.Dep.Var   
 Length:6989        Length:6989        Length:6989        Length:6989       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
\end{verbatim}

The \texttt{summary()} function shows you the name of all the columns in
the data frame and what each column contains.

When you import a data frame into \emph{R}, \emph{R} automatically
decides what type of data each column contains. Any data frame columns
where all cells contain only numbers are assumed to \texttt{numeric} or
\texttt{integer} data (depending on if there are decimal values). Any
columns that include letters will be assumed to be \texttt{character}
data.

For \texttt{numeric} or \texttt{integer} data (like \texttt{YOB}, or
year of birth of the speakers in the \texttt{td} data), the
\texttt{summary()} function will tell you the mean, the median, the
minimum value, the maximum value, and the values of the first and third
quartiles. The mean is the arithmetic mean, which is the sum of all the
values in a column divided by the number of values in a column. Fifty
percent of the values in the column are equal to or less than the mean
and 50\% of the values in the column are greater than or less than the
mean. The mean can also be thought of as the 2nd quartile. The median is
exact middle point of the values in the column ordered from smallest to
largest. For \emph{normally distributed} data, the mean and the median
should be close to the same value. Not all data, however, is normally
distributed, which is sometimes a problem, and sometimes not a problem.
If a certain test expects numerical data to be normally distributed
these instructions will explain what to do, but for now, it's just good
to know what mean and median indicate. Twenty-five percent of the values
in the column are equal to or less than the 1st quartile and 75\% of the
values in the column are equal to or less than the 3rd quartile. The
minimum value is the lowest value in a column; the maximum value is the
highest number in a column. These values can be used to construct a
\textbf{box and whisker} plot:

\begin{figure}

{\centering \includegraphics{030_lvcr_files/figure-pdf/fig-yob-1.pdf}

}

\caption{\label{fig-yob}Box and whisker plot of \texttt{YOB} (Year of
Birth) in the \texttt{td} data frame}

\end{figure}

The bottom \textbf{whisker} ends at the minimum value of 1910. The
bottom line of the \textbf{box} displays the first quartile value of
1952. The thick bar in the middle of the \textbf{box} is at the second
quartile value/mean of 1965. The top line of the \emph{box} ends at the
third quartile value of 1991. The range from the first quartile to the
third quartile is called the \textbf{interquartile range}. The top
\textbf{whisker} ends at the maximum value of 1999. Sometimes extremely
high or extremely low values are more than \(1.5\times\) the
interquartile range from the top or bottom of the box. In these cases
the whiskers will extend out to the last value within \(1.5\times\) the
interquartile range and anything beyond that will be an \textbf{outlier}
and identified with a small circle, as in Figure~\ref{fig-tokens}.

\begin{figure}

{\centering \includegraphics{030_lvcr_files/figure-pdf/fig-tokens-1.pdf}

}

\caption{\label{fig-tokens}Box and whisker plot of the number of tokens
per speaker in the \texttt{td} data frame}

\end{figure}

The function \texttt{names()} returns a vector (a series of items in a
line, separated by commas) of the column names. This function can be
useful as a quick way to get the names of each column. You will need to
use these names quite often when writing other commands.
\texttt{colnames()} returns the same information; \texttt{ls()} returns
the same information, but ordered alphabetically.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "Dep.Var"         "Stress"          "Category"        "Morph.Type"     
 [5] "Before"          "After"           "Speaker"         "YOB"            
 [9] "Sex"             "Education"       "Job"             "Phoneme.Dep.Var"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "Dep.Var"         "Stress"          "Category"        "Morph.Type"     
 [5] "Before"          "After"           "Speaker"         "YOB"            
 [9] "Sex"             "Education"       "Job"             "Phoneme.Dep.Var"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ls}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "After"           "Before"          "Category"        "Dep.Var"        
 [5] "Education"       "Job"             "Morph.Type"      "Phoneme.Dep.Var"
 [9] "Sex"             "Speaker"         "Stress"          "YOB"            
\end{verbatim}

The function \texttt{str()} describes the structure of a data frame. It
reports similar information as \texttt{summary()} but does not include
descriptions of each column; however, the layout of the information is
sometimes a little easier to read, especially if your data frame has
many columns. Here we can see that \texttt{YOB} is categorized as
\texttt{int} (integer) data and all the other columns are \texttt{chr}
(character) data.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
'data.frame':   6989 obs. of  12 variables:
 $ Dep.Var        : chr  "Realized" "Realized" "Realized" "Deletion" ...
 $ Stress         : chr  "Stressed" "Stressed" "Stressed" "Stressed" ...
 $ Category       : chr  "Function" "Function" "Function" "Function" ...
 $ Morph.Type     : chr  "Mono" "Mono" "Mono" "Mono" ...
 $ Before         : chr  "Vowel" "Vowel" "Vowel" "Vowel" ...
 $ After          : chr  "Pause" "Pause" "Pause" "Pause" ...
 $ Speaker        : chr  "BOUF65" "CHIF55" "CLAF52" "CLAM73" ...
 $ YOB            : int  1965 1955 1952 1973 1915 1941 1953 1953 1958 1946 ...
 $ Sex            : chr  "F" "F" "F" "M" ...
 $ Education      : chr  "Educated" "Educated" "Educated" "Not Educated" ...
 $ Job            : chr  "White" "White" "Service" "Blue" ...
 $ Phoneme.Dep.Var: chr  "t--Affricate" "t--Fricative" "t--Affricate" "t--Deletion" ...
\end{verbatim}

\texttt{head()} will return the first six lines of the data frame.
\texttt{tail()} provides the last six. For either you can change the
number of lines reported using the option \texttt{n=}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Dep.Var   Stress Category Morph.Type Before After Speaker  YOB Sex
1 Realized Stressed Function       Mono  Vowel Pause  BOUF65 1965   F
2 Realized Stressed Function       Mono  Vowel Pause  CHIF55 1955   F
3 Realized Stressed Function       Mono  Vowel Pause  CLAF52 1952   F
4 Deletion Stressed Function       Mono  Vowel Pause  CLAM73 1973   M
5 Realized Stressed Function       Mono  Vowel Pause  DONF15 1915   F
6 Realized Stressed Function       Mono  Vowel Pause  DONM41 1941   M
     Education     Job Phoneme.Dep.Var
1     Educated   White    t--Affricate
2     Educated   White    t--Fricative
3     Educated Service    t--Affricate
4 Not Educated    Blue     t--Deletion
5 Not Educated Service    t--Fricative
6 Not Educated    Blue    t--Fricative
\end{verbatim}

The numbers on the left side of the output are the row number in the
data frame.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tail}\NormalTok{(td, }\AttributeTok{n =} \DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
      Dep.Var   Stress Category Morph.Type Before After Speaker  YOB Sex
6980 Realized Stressed Function       Mono  Vowel Vowel  STEM42 1942   M
6981 Realized Stressed Function       Mono  Vowel Vowel  VIKF91 1991   F
6982 Realized Stressed Function       Mono  Vowel Vowel  VIKF91 1991   F
6983 Realized Stressed  Lexical       Mono  Nasal Pause  PACM94 1994   M
6984 Deletion Stressed  Lexical       Mono      S Pause  INGM84 1984   M
6985 Realized Stressed  Lexical       Mono      S Vowel  INGM84 1984   M
6986 Realized Stressed Function       Mono  Vowel Pause  GARF16 1916   F
6987 Realized Stressed  Lexical       Mono  Vowel Pause  GARF87 1987   F
6988 Deletion Stressed  Lexical       Mono  Vowel Pause  GARF87 1987   F
6989 Realized Stressed  Lexical       Mono  Vowel Pause  GARF87 1987   F
        Education     Job Phoneme.Dep.Var
6980 Not Educated Service d--Glottal Stop
6981      Student Student         d--Flap
6982      Student Student         d--Flap
6983      Student Student            d--T
6984     Educated Service     t--Deletion
6985     Educated Service t--Glottal Stop
6986 Not Educated Service    t--Fricative
6987     Educated   White            d--T
6988     Educated   White     d--Deletion
6989     Educated   White            d--D
\end{verbatim}

\hypertarget{types-of-data}{%
\subsubsection{Types of Data}\label{types-of-data}}

There are other types of data beside \texttt{numerical} (like
\texttt{YOB} in the \texttt{td} data) and \texttt{character} (like all
other columns in the \texttt{td} data).

\begin{table}
\caption{Types of data in \textit{R}}
\begin{tabular}{lp{.33\textwidth}p{.33\textwidth}}
\toprule
 Data Type & Description & Example\\                                                                  \texttt{logical} & either \texttt{TRUE} or \texttt{FALSE} & The answer to a question like "is \texttt{x} a number?", etc.\\       
 \texttt{numeric} & any real number, positive or negative, with or without decimal values & Vowel formant measurements, position in an audio file, household income, etc.\\ 
\texttt{double}& any real number, positive or negative, with or without decimal values (identical to \texttt{numeric}) & Vowel formant measurements, position in an audio file, household income, etc.\\
\texttt{integer}& whole numbers and their negative counterparts & year of birth, year of data collection, number of occurrences of something, etc.\\
\texttt{complex} & data that includes imaginary or unknown elements & the pythagorian theroem, i.e., $a^2 + b^2 = c^2$, where $a$, $b$, and $c$ are unknown\\
\texttt{character} & single characters (like \texttt{'F'}) or \textbf{strings} (like \texttt{"female"}) & gender, speaker name, etc.\\ 
\texttt{raw} & raw bytes  & Anything expressed in bytes \\
\end{tabular}
\end{table}

\begin{tcolorbox}[enhanced jigsaw, rightrule=.15mm, titlerule=0mm, coltitle=black, opacityback=0, arc=.35mm, left=2mm, toprule=.15mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Note}, toptitle=1mm, colback=white, opacitybacktitle=0.6, colframe=quarto-callout-note-color-frame, breakable, colbacktitle=quarto-callout-note-color!10!white, bottomtitle=1mm, bottomrule=.15mm, leftrule=.75mm]
Character data is always enclosed in either single quotes
\texttt{\textquotesingle{}\ \textquotesingle{}} or double quotes
\texttt{"\ "}. It is common practice to use single quotes for single
characters and double quotes for strings, though either type of
quotation marks will work with either data type.

\texttt{double} is short for ``double precision floating point
numbers''. Don't worry about the difference between \texttt{numeric} and
\texttt{double}, because it doesn't really matter.
\end{tcolorbox}

It is uncommon to use \texttt{raw} data in sociolinguistics. Anything
can be expressed in bytes. There are two functions to convert from
characters to bytes, and bytes to characters. To go from characters to
bytes:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{raw\_variable }\OtherTok{\textless{}{-}} \FunctionTok{charToRaw}\NormalTok{(}\StringTok{"Sociolinguistics is fun"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(raw\_variable)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] 53 6f 63 69 6f 6c 69 6e 67 75 69 73 74 69 63 73 20 69 73 20 66 75 6e
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{class}\NormalTok{(raw\_variable))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "raw"
\end{verbatim}

Above the function \texttt{charToRaw()} converts the string
\texttt{"Sociolinguistics\ is\ fun"} to bytes and assigns that raw data
to the object \texttt{raw\_variable}. Next the \texttt{print()} function
displays in \emph{R} the contents of the variable
\texttt{raw\_variable}. The \texttt{class()} function returns the type
of data contained within a variable. To convert back to characters:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{char\_variable }\OtherTok{\textless{}{-}} \FunctionTok{rawToChar}\NormalTok{(raw\_variable)}
\FunctionTok{print}\NormalTok{(char\_variable)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Sociolinguistics is fun"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{class}\NormalTok{(char\_variable))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "character"
\end{verbatim}

\hypertarget{types-of-data-structures}{%
\subsubsection{Types of Data
Structures}\label{types-of-data-structures}}

A \textbf{vector} and a \textbf{list} are the most basic types of data
structures. A \textbf{vector} is a collection of elements, most commonly
a collection of \texttt{character}, \texttt{logical}, \texttt{integer},
or \texttt{numeric} values. Values can be combined into a vector using
the concatenating function \texttt{c()}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{simple.vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Labov"}\NormalTok{, }\StringTok{"Fishman"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(simple.vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Labov"   "Fishman"
\end{verbatim}

We can explore the vector using some of the same functions we've already
seen.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{length}\NormalTok{(simple.vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(simple.vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "character"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(simple.vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 chr [1:2] "Labov" "Fishman"
\end{verbatim}

\textbf{Lists} are like \textbf{vectors} but can contain a mixture of
different data types. Characters must be in quotation marks. Numbers in
quotation marks will be categorized as characters. Numeric data is
numbers without quotation marks. Integers are specificed by adding
\texttt{L} after the number. Logical values are either \texttt{TRUE} or
\texttt{FALSE} in all capital letters.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{simple.list }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\StringTok{"Labov"}\NormalTok{, }\StringTok{"Fishman"}\NormalTok{, }\StringTok{"2001"}\NormalTok{, }\DecValTok{1963}\NormalTok{,}
    \FloatTok{1.5}\NormalTok{, 1974L, }\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{print}\NormalTok{(simple.list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[[1]]
[1] "Labov"

[[2]]
[1] "Fishman"

[[3]]
[1] "2001"

[[4]]
[1] 1963

[[5]]
[1] 1.5

[[6]]
[1] 1974

[[7]]
[1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{length}\NormalTok{(simple.list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(simple.list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "list"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(simple.list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
List of 7
 $ : chr "Labov"
 $ : chr "Fishman"
 $ : chr "2001"
 $ : num 1963
 $ : num 1.5
 $ : int 1974
 $ : logi TRUE
\end{verbatim}

You will notice that the results of the \texttt{str()} function show
that \texttt{Labov}, \texttt{Fishman} and \texttt{2001} are all
categorized as \texttt{chr} (character); \texttt{1963} and \texttt{1.5}
are categorized as \texttt{num} (numeric); \texttt{1974} is categorized
as \texttt{int} (integer); and \texttt{TRUE} is categorized as
\texttt{logi} (logical).

Lists can be bigger than just one group of data. Items in a list can
also be more complex than a single value.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{complex.list }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\AttributeTok{a =} \StringTok{"John Baugh"}\NormalTok{, }\AttributeTok{b =}\NormalTok{ simple.vector,}
    \AttributeTok{c =}\NormalTok{ simple.list, }\AttributeTok{d =} \FunctionTok{head}\NormalTok{(td))}
\FunctionTok{print}\NormalTok{(complex.list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$a
[1] "John Baugh"

$b
[1] "Labov"   "Fishman"

$c
$c[[1]]
[1] "Labov"

$c[[2]]
[1] "Fishman"

$c[[3]]
[1] "2001"

$c[[4]]
[1] 1963

$c[[5]]
[1] 1.5

$c[[6]]
[1] 1974

$c[[7]]
[1] TRUE


$d
   Dep.Var   Stress Category Morph.Type Before After Speaker  YOB Sex
1 Realized Stressed Function       Mono  Vowel Pause  BOUF65 1965   F
2 Realized Stressed Function       Mono  Vowel Pause  CHIF55 1955   F
3 Realized Stressed Function       Mono  Vowel Pause  CLAF52 1952   F
4 Deletion Stressed Function       Mono  Vowel Pause  CLAM73 1973   M
5 Realized Stressed Function       Mono  Vowel Pause  DONF15 1915   F
6 Realized Stressed Function       Mono  Vowel Pause  DONM41 1941   M
     Education     Job Phoneme.Dep.Var
1     Educated   White    t--Affricate
2     Educated   White    t--Fricative
3     Educated Service    t--Affricate
4 Not Educated    Blue     t--Deletion
5 Not Educated Service    t--Fricative
6 Not Educated    Blue    t--Fricative
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(complex.list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
List of 4
 $ a: chr "John Baugh"
 $ b: chr [1:2] "Labov" "Fishman"
 $ c:List of 7
  ..$ : chr "Labov"
  ..$ : chr "Fishman"
  ..$ : chr "2001"
  ..$ : num 1963
  ..$ : num 1.5
  ..$ : int 1974
  ..$ : logi TRUE
 $ d:'data.frame':  6 obs. of  12 variables:
  ..$ Dep.Var        : chr [1:6] "Realized" "Realized" "Realized" "Deletion" ...
  ..$ Stress         : chr [1:6] "Stressed" "Stressed" "Stressed" "Stressed" ...
  ..$ Category       : chr [1:6] "Function" "Function" "Function" "Function" ...
  ..$ Morph.Type     : chr [1:6] "Mono" "Mono" "Mono" "Mono" ...
  ..$ Before         : chr [1:6] "Vowel" "Vowel" "Vowel" "Vowel" ...
  ..$ After          : chr [1:6] "Pause" "Pause" "Pause" "Pause" ...
  ..$ Speaker        : chr [1:6] "BOUF65" "CHIF55" "CLAF52" "CLAM73" ...
  ..$ YOB            : int [1:6] 1965 1955 1952 1973 1915 1941
  ..$ Sex            : chr [1:6] "F" "F" "F" "M" ...
  ..$ Education      : chr [1:6] "Educated" "Educated" "Educated" "Not Educated" ...
  ..$ Job            : chr [1:6] "White" "White" "Service" "Blue" ...
  ..$ Phoneme.Dep.Var: chr [1:6] "t--Affricate" "t--Fricative" "t--Affricate" "t--Deletion" ...
\end{verbatim}

In the list \texttt{complex.list} column \texttt{a} contains only one
value: \texttt{John\ Baugh}. Column \texttt{b} contains our
\texttt{simple.vector}, column \texttt{c} contains our
\texttt{simple.list}, and column \texttt{d} includes the first six rows
of the \texttt{td} data (which itself has columns). To access the values
from columns within columns you can use multiple \texttt{\$} operators.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(complex.list}\SpecialCharTok{$}\NormalTok{a)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "John Baugh"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(complex.list}\SpecialCharTok{$}\NormalTok{d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Dep.Var   Stress Category Morph.Type Before After Speaker  YOB Sex
1 Realized Stressed Function       Mono  Vowel Pause  BOUF65 1965   F
2 Realized Stressed Function       Mono  Vowel Pause  CHIF55 1955   F
3 Realized Stressed Function       Mono  Vowel Pause  CLAF52 1952   F
4 Deletion Stressed Function       Mono  Vowel Pause  CLAM73 1973   M
5 Realized Stressed Function       Mono  Vowel Pause  DONF15 1915   F
6 Realized Stressed Function       Mono  Vowel Pause  DONM41 1941   M
     Education     Job Phoneme.Dep.Var
1     Educated   White    t--Affricate
2     Educated   White    t--Fricative
3     Educated Service    t--Affricate
4 Not Educated    Blue     t--Deletion
5 Not Educated Service    t--Fricative
6 Not Educated    Blue    t--Fricative
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(complex.list}\SpecialCharTok{$}\NormalTok{d}\SpecialCharTok{$}\NormalTok{Job)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "White"   "White"   "Service" "Blue"    "Service" "Blue"   
\end{verbatim}

Generally, in LVC analysis we do not deal often with either simple
vectors or lists; instead, most of our data is in a spreadsheet-like
format, which in \emph{R} is a \textbf{data frame}.

\textbf{Data frames} are a special type of \textbf{list} in which every
element in the \textbf{list} has the same length (unlike, for example,
the \texttt{complex.list} above). \textbf{Data frames} can have
additional annotations, like \texttt{rownames()}. Some statisticians use
\texttt{rownames()} for things like \texttt{participantID},
\texttt{sampleID}, or some other unique identifier. Most of the time
(and for our purposes), \texttt{rownames()} are not useful given that we
have multiple rows from the same speaker/interview, etc.

\hypertarget{factors-and-comments}{%
\subsubsection{Factors and Comments}\label{factors-and-comments}}

A \emph{factor} in \emph{R} is a special type of variable or data type
that, in theory, has a limited number of values. Each value is called a
\emph{level}. Any \textbf{vector} or \textbf{data frame} column of
\texttt{character} or \texttt{integer} values can be a \textbf{factor}.
Most non-numerical data in LVC is generally thought of as a
\textbf{factor} already, so knowing how to convert \textbf{vectors} or
\textbf{data frame} columns to factors is important. For example, in the
\texttt{td} data, the column \texttt{Stress} contains only two options:
\texttt{Stressed} and \texttt{Unstressed}. Because this column contains
letters, when we imported it into \emph{R}, it was automatically
categorized as \texttt{character} data. This is probably the best option
for a column that, for example, contained the broader context of a
token. For \texttt{Stress}, however, it is better for our purposes for
\emph{R} to consider the column as containing a \textbf{factor} with two
discrete levels. Below is the code to convert \texttt{Stress} into a
\textbf{factor}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Determine the class of the column Stress in the}
\CommentTok{\# date frame td}
\FunctionTok{class}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Stress)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "character"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Convert Stress to a column to a factor}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Stress }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Stress)}
\CommentTok{\# Verify class of Stress column}
\FunctionTok{class}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Stress)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "factor"
\end{verbatim}

Notice the \textbf{comments} in the code above. In \emph{R} any line
that begins with a \texttt{\#} is not evaluated. This is called
\emph{commenting out} a line. We use \texttt{\#} to include notes in our
codes, or to keep code in our script file but have \emph{R} ignore it.
This can be useful in order to keep track of the steps you are taking in
an analysis (see also
\href{https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections-in-the-RStudio-IDE}{this
tutorial} on organizing code using \texttt{\#})

Columns within a data frame can be specified using the \texttt{\$}
operator So, above, we tell \emph{R} to assign (using the assignment
operator \texttt{\textless{}-}) the values of the original
\texttt{td\$Stress} column, converted into \textbf{factors}, back to the
column \texttt{td\$Stress}. In other words, we are replacing the
original column \texttt{td\$Stress} with a converted version of itself.
Now, look how the output of the \texttt{summary()} function changes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Dep.Var                 Stress       Category          Morph.Type       
 Length:6989        Stressed  :6555   Length:6989        Length:6989       
 Class :character   Unstressed: 434   Class :character   Class :character  
 Mode  :character                     Mode  :character   Mode  :character  
                                                                           
                                                                           
                                                                           
    Before             After             Speaker               YOB      
 Length:6989        Length:6989        Length:6989        Min.   :1915  
 Class :character   Class :character   Class :character   1st Qu.:1952  
 Mode  :character   Mode  :character   Mode  :character   Median :1965  
                                                          Mean   :1967  
                                                          3rd Qu.:1991  
                                                          Max.   :1999  
     Sex             Education             Job            Phoneme.Dep.Var   
 Length:6989        Length:6989        Length:6989        Length:6989       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
\end{verbatim}

We get the number of observations of each level of \texttt{td\$Stress}
instead of just the number of rows (i.e.~the \texttt{length} of the
column).

To get the levels of a \textbf{factor} we can use the function
\texttt{levels()} and to get the number of levels, we can use the
function \texttt{nlevels()}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{levels}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Stress)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Stressed"   "Unstressed"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nlevels}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Stress)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2
\end{verbatim}

\hypertarget{more-exploring}{%
\subsection{More Exploring}\label{more-exploring}}

If you only want information from a single column of the data frame, you
can use the operator \texttt{\$} to specify which column of \texttt{td}
you want. Here the column `Sex' is specified.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Length     Class      Mode 
     6989 character character 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{levels}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
NULL
\end{verbatim}

The \texttt{Sex} column is still categorized as \texttt{character} data
and so \texttt{summary()} only return the number of rows
(\texttt{length}) of the column and there are no levels. To get the
information we want about the \texttt{Sex} column (i.e., how many tokens
are from male speakers and how many are from women speakers) we need to
convert it to a factor first. We can either convert the the column to a
factor column, or we can use the \texttt{as.factor()} function to have
\emph{R} treat is as a factor in just the following code.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{as.factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Sex))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   F    M 
3776 3213 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{levels}\NormalTok{(}\FunctionTok{as.factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Sex))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "F" "M"
\end{verbatim}

The following code changes all the character class columns to factors.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Start with a fresh import of the (t, d) data}
\CommentTok{\# into R, downloading it directly}
\NormalTok{td }\OtherTok{\textless{}{-}} \FunctionTok{read.delim}\NormalTok{(}\StringTok{"https://www.dropbox.com/s/jxlfuogea3lx2pu/deletiondata.txt?dl=1"}\NormalTok{)}

\CommentTok{\# or using the version saved locally in a folder}
\CommentTok{\# Data in the same location as your script file}
\NormalTok{td }\OtherTok{\textless{}{-}} \FunctionTok{read.delim}\NormalTok{(}\StringTok{"Data/deletiondata.txt"}\NormalTok{)}

\CommentTok{\# Now convert each character column into a factor}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Dep.Var }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Dep.Var)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Stress }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Stress)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Category }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Category)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Morph.Type }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Morph.Type)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Before }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Before)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{After }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{After)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Speaker }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Speaker)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Sex }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Sex)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Education }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Education)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Job }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Job)}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Phoneme.Dep.Var }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Phoneme.Dep.Var)}
\end{Highlighting}
\end{Shaded}

\hypertarget{the-td-data}{%
\subsection{The (t/d) Data}\label{the-td-data}}

Let's look at the data now that all the character columns are factors.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(td)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
     Dep.Var            Stress         Category        Morph.Type  
 Deletion:1747   Stressed  :6555   Function: 739   Mono     :5236  
 Realized:5242   Unstressed: 434   Lexical :6250   Past     : 782  
                                                   Semi-Weak: 971  
                                                                   
                                                                   
                                                                   
                                                                   
             Before           After         Speaker          YOB       Sex     
 Liquid         : 269   Consonant: 709   GARF87 : 224   Min.   :1915   F:3776  
 Nasal          : 209   H        : 246   INGM84 : 212   1st Qu.:1952   M:3213  
 Other Fricative: 130   Pause    :5248   MARM92 : 176   Median :1965           
 S              : 332   Vowel    : 786   HANF83 : 139   Mean   :1967           
 Stop           : 249                    CHIF55 : 135   3rd Qu.:1991           
 Vowel          :5800                    GARF16 : 132   Max.   :1999           
                                         (Other):5971                          
        Education         Job           Phoneme.Dep.Var
 Educated    :3006   Blue   :1068   t--Deletion : 981  
 Not Educated:2184   Service:2895   t--Fricative: 973  
 Student     :1799   Student:1799   t--T        : 830  
                     White  :1227   d--Deletion : 766  
                                    t--Affricate: 667  
                                    d--T        : 583  
                                    (Other)     :2189  
\end{verbatim}

As shown by the \texttt{summary(td)} results above, the first column in
the (t, d) deletion data is called \texttt{Dep.Var} and it includes two
levels: \texttt{Realized} and \texttt{Deletion}. These two levels
represent the two options for each token of (t, d). The values after
each level are how many rows are coded with that level. In other words,
there are 1,747 rows (or tokens) of \texttt{Deletion} and there are
5,242 rows (or tokens) of \texttt{Realized}. Notice that the order of
the factor levels is alphabetical. There is a column labelled
\texttt{Stress} which indicates if the (t, d) token is in a stressed or
unstressed syllable. The \texttt{Category} column indicates if the word
in which the (t, d) token appears is a function or lexical word.
\texttt{Morph.Type} indicates if the (t, d) occurs in a monomorpheme
(like \emph{fist}), a semi-weak simple past-tense verb (like
\emph{dealt} ) in which there is a vowel change and a (t,d) sound is
added, or a weak simple past-tense verb (like \emph{walked}) in which
just /\emph{-ed}/ is added. \texttt{Before} indicates the type of sound
preceding the (t, d) and \texttt{After} indicates the sound following
the (t, d). \texttt{Speaker} is a unique identifier for each participant
in the data (only the first six are displayed, though); \texttt{YOB}
indicates the speaker's year of birth, \texttt{Sex} his or her
sex\footnote{These were the only two sex/gender identities reported by
  speakers in this data.}, \texttt{Education} his or her education
level, and \texttt{Job} his or her job type. Finally,
\texttt{Phoneme.Dep.Var} indicates the canonical underlying phoneme of
the (t, d) token and a more detailed coding of the dependent variable.



\end{document}
