% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  10pt,
  letterpaper]{article}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
  \setmainfont[]{Charis SIL}
  \setmonofont[]{Monaco}
  \setmathfont[]{Monaco}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin = 1in]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{tabularx}
\usepackage{threeparttable}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{tipa}
\let\Oldtexttt\texttt
\renewcommand\texttt[1]{{\ttfamily\color{BrickRed}#1}}
\usepackage{authoraftertitle}
\usepackage{fancyhdr}
\pagestyle{fancy}
\rfoot{\copyright Matt Hunt Gardner}
\cfoot{\thepage}
\lhead{Doing LVC with \textit{R}: \MyTitle}
\rhead{}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Table}
\else
  \newcommand\figurename{Table}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
% Make links footnotes instead of hotlinks:
\DeclareRobustCommand{\href}[2]{#2\footnote{\url{#1}}}
\hypersetup{
  pdftitle={Mixed-Efects Logistic Regression Analysisː Part 4},
  pdfauthor={Matt Hunt Gardner},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Mixed-Efects Logistic Regression Analysisː Part 4}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{from
\href{https://lingmethodshub.github.io/content/R/lvc_r/}{Doing LVC with
\emph{R}}}
\author{Matt Hunt Gardner}
\date{3/11/23}

\begin{document}
\maketitle
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[breakable, enhanced, frame hidden, interior hidden, borderline west={3pt}{0pt}{shadecolor}, sharp corners, boxrule=0pt]}{\end{tcolorbox}}\fi

Before you proceed with this section, please make sure that you have
your data loaded and modified based on the code
\href{https://lingmethodshub.github.io/content/R/lvc_r/050_lvcr.html}{here}
and that \texttt{Dep.Var} is
\href{https://lingmethodshub.github.io/content/R/lvc_r/110_lvcr.html}{re-coded
such that \texttt{Deletion} is the second factor}. Next, you
\href{https://lingmethodshub.github.io/content/R/lvc_r/112_lvcr.html}{set
the global \emph{R} options to employ sum contrast coding}.

\hypertarget{treatment-contrasts-vs.-reference-value}{%
\section{Treatment Contrasts (vs.~reference
value)}\label{treatment-contrasts-vs.-reference-value}}

Rather than compare levels of each parameter to the
\href{https://lingmethodshub.github.io/content/R/lvc_r/112_lvcr.html}{mean
of that parameter}, you can instead specify one level as the reference
level and then compare every other level to it (see
\href{https://lingmethodshub.github.io/content/R/lvc_r/110_lvcr.html}{Part
1}). To do this you need to set the global contrasts to
\texttt{contr.treatment}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Treatment Contrasts (vs. reference)}
\FunctionTok{options}\NormalTok{(}\AttributeTok{contrasts =} \FunctionTok{c}\NormalTok{(}\StringTok{"contr.treatment"}\NormalTok{, }\StringTok{"contr.poly"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

This is actually the more common way to perform a mixed-effects logistic
regression outside of sociolinguistics. With the contrasts now set to
treatment contrasts you can re-run your most-parsimonious model.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Most Parsimonious Model: Generalized linear}
\CommentTok{\# mixed effects model with the fixed main effects}
\CommentTok{\# of Before, After.New, Morph.Type, Stress,}
\CommentTok{\# Phoneme, and the random effect of Speaker}
\FunctionTok{library}\NormalTok{(lme4)}
\NormalTok{td.glmer.parsimonious }\OtherTok{\textless{}{-}} \FunctionTok{glmer}\NormalTok{(Dep.Var }\SpecialCharTok{\textasciitilde{}}\NormalTok{ After.New }\SpecialCharTok{+}
\NormalTok{    Morph.Type }\SpecialCharTok{+}\NormalTok{ Before }\SpecialCharTok{+}\NormalTok{ Stress }\SpecialCharTok{+}\NormalTok{ Phoneme }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ Speaker),}
    \AttributeTok{data =}\NormalTok{ td, }\AttributeTok{family =} \StringTok{"binomial"}\NormalTok{, }\AttributeTok{control =} \FunctionTok{glmerControl}\NormalTok{(}\AttributeTok{optCtrl =} \FunctionTok{list}\NormalTok{(}\AttributeTok{maxfun =} \DecValTok{20000}\NormalTok{),}
        \AttributeTok{optimizer =} \StringTok{"bobyqa"}\NormalTok{))}
\FunctionTok{summary}\NormalTok{(td.glmer.parsimonious)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: binomial  ( logit )
Formula: Dep.Var ~ After.New + Morph.Type + Before + Stress + Phoneme +  
    (1 | Speaker)
   Data: td
Control: glmerControl(optCtrl = list(maxfun = 20000), optimizer = "bobyqa")

     AIC      BIC   logLik deviance df.resid 
    1114     1175     -545     1090     1177 

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-5.223 -0.488 -0.259  0.495 14.033 

Random effects:
 Groups  Name        Variance Std.Dev.
 Speaker (Intercept) 0.796    0.892   
Number of obs: 1189, groups:  Speaker, 66

Fixed effects:
                      Estimate Std. Error z value Pr(>|z|)    
(Intercept)              0.902      0.265    3.40  0.00067 ***
After.NewPause          -3.015      0.255  -11.82  < 2e-16 ***
After.NewVowel          -2.506      0.284   -8.82  < 2e-16 ***
Morph.TypePast          -2.319      0.296   -7.84  4.7e-15 ***
Morph.TypeSemi-Weak      1.039      0.281    3.70  0.00022 ***
BeforeNasal              1.100      0.276    3.99  6.6e-05 ***
BeforeOther Fricative    0.692      0.407    1.70  0.08907 .  
BeforeS                  1.306      0.317    4.11  3.9e-05 ***
BeforeStop              -0.224      0.299   -0.75  0.45349    
StressUnstressed         1.598      0.275    5.81  6.2e-09 ***
Phonemet                -0.573      0.255   -2.25  0.02462 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) Aft.NP Aft.NV Mrp.TP M.TS-W BfrNsl BfrOtF BeforS BfrStp
After.NewPs -0.464                                                        
After.NwVwl -0.294  0.529                                                 
Mrph.TypPst -0.232  0.260  0.190                                          
Mrph.TypS-W -0.217  0.009  0.050  0.058                                   
BeforeNasal -0.221 -0.343 -0.187 -0.047  0.222                            
BfrOthrFrct -0.098 -0.181 -0.041 -0.498  0.238  0.337                     
BeforeS     -0.056 -0.451 -0.132 -0.102  0.337  0.553  0.480              
BeforeStop  -0.259  0.016  0.039 -0.132  0.389  0.443  0.472  0.557       
StrssUnstrs  0.059 -0.230 -0.511 -0.046  0.123 -0.047  0.092  0.185 -0.089
Phonemet    -0.386  0.265  0.009  0.126 -0.337 -0.214 -0.372 -0.608 -0.488
            StrssU
After.NewPs       
After.NwVwl       
Mrph.TypPst       
Mrph.TypS-W       
BeforeNasal       
BfrOthrFrct       
BeforeS           
BeforeStop        
StrssUnstrs       
Phonemet    -0.107
\end{verbatim}

The treatment contrast output looks very much like the model you
constructed using sum contrasts (you'll notice that the measures of
model fit and the description of the random effects are identical), but
there are a few key differences. Firstly, the listed levels of each
parameter are now written-out rather than just being numbers. This makes
treatment contrast results somewhat easier to interpret. The levels that
are listed are all the levels other than the first in that level's
factor order. The default order of factors is alphabetic, though you can
change this (as you did
\href{https://lingmethodshub.github.io/content/R/lvc_r/112_lvcr.html}{previously}
for \texttt{Dep.Var} and \texttt{Age.Group}). The first level in each
parameter is set as the \textbf{reference level}. The reference level
for \texttt{Before} is \texttt{Liquid}, the reference level for
\texttt{After.New} is \texttt{Consonant}, the reference level for
\texttt{Morph.Type} is \texttt{Mono}, the reference level for
\texttt{Stress} is \texttt{Stressed}, and the reference level for
\texttt{Phoneme} is \texttt{d}.

The \texttt{(Intercept)} value is the likelihood of a given token being
the application value if that token is coded with all the reference
levels. In other words, \texttt{0.902} is the likelihood, in log odds,
of a token being \texttt{Deletion} if that token has a preceding liquid,
a following consonant, is mono-morphemic, is stressed, and is an
underlying /d/. The estimate for each level is the change in likelihood
if that parameter changes to the given level. The difference in
likelihood resulting from a token being unstressed, instead of stressed,
but with all other parameter settings the same, is \texttt{1.598} In
other words, a token with a preceding liquid, following consonant, that
is mono-morphemic, that is an underlying /d/, and is unstressed is
\(2.500\) log odds (\(0.902+1.598\)) or \(92\%\) probability.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plogis}\NormalTok{(}\FloatTok{2.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.92
\end{verbatim}

\begin{tcolorbox}[enhanced jigsaw, toptitle=1mm, colframe=quarto-callout-warning-color-frame, toprule=.15mm, opacityback=0, rightrule=.15mm, arc=.35mm, left=2mm, breakable, leftrule=.75mm, colbacktitle=quarto-callout-warning-color!10!white, bottomtitle=1mm, opacitybacktitle=0.6, coltitle=black, bottomrule=.15mm, titlerule=0mm, title=\textcolor{quarto-callout-warning-color}{\faExclamationTriangle}\hspace{0.5em}{Warning}, colback=white]

With treatment contrasts you \textbf{must}
\href{https://lingmethodshub.github.io/content/R/lvc_r/040_lvcr.html}{center
your continuous variables}.

\end{tcolorbox}

With sum contrasts the reference ``level'' is the mean for each
parameter not a particular level of the parameter; this includes
continuous factors. For this reason, whether or not you center
continuous factors with sum contrast coding doesn't really matter. The
reference level for treatment contrast coding is the first level of the
parameter. For continuous variables this means the reference level is
\(0\). For some applications this might be okay --- for example, if your
continuous variable is voice onset time. For most of your applications,
though, where continuous factors represent age, this is not desirable.
Zero is not a meaningful year of birth or a meaningful age. For this
reason we center these factors, thereby changing the mean or average age
to zero (so that \(0\) equals something meaningful), and all other ages
as differences from that mean. This results in the intercept of a
treatment contrast model being the overall likelihood when all the
discrete parameters are set to their first value and the continuous
parameters set to their mean value.

The \emph{p}-value for each level represents whether or not the
resultant difference (e.g., estimate) is significantly different from
zero. The \emph{p}-value for \texttt{BeforeStop} is \(0.45350\). This is
greater than \(0.05\), and therefore you say there is not a significant
difference in likelihood between tokens with a preceding liquid and
tokens with a preceding stop. This changes the constraint hierarchy for
this factor group to \texttt{S} \textgreater{} \texttt{Nasal}
\textgreater{} \texttt{Other\ Fricative} \textgreater{}
\texttt{Liquid/Stop}. It also justifies re-coding these two factors into
a single parameter level.

\begin{table}
\begin{center}
\caption*{Treatment contrasts vs sum contrasts} 
\begin{tabular}{rp{.33\textwidth}p{.37\textwidth}}
\toprule
& \multicolumn{1}{c}{Treatment Contrasts} & \multicolumn{1}{c}{Sum Contrasts}\\
\midrule
Point of comparison & Reference level & Mean of parameter\\
Level estimate & Difference in likelihood \newline from reference level & Difference in likelihood \newline from parameter mean\\
Intercept & Likelihood with all reference levels & Grand Mean\newline (mean of parameter means)\\
Missing value & Reference level\newline(first level of factor) & Last level of factor\\
Missing value estimate & 0 & 0 - sum of remaining estimates\\
Continuous Parameters & Must center & Should center\\
\bottomrule
\end{tabular}
\end{center}
\end{table}

As before, the correlation of fixed effects suggests where there might
be non-orthogonality. Values over \(|0.3|\) should be investigated,
those above \(|0.7|\) should be seriously investigated. Calculating the
Variable Inflation Factor (VIF) and Condition Number (\(\kappa\)) is, as
always, useful in determining if these correlations are within
acceptable limits of collinearity (as discussed in
\href{https://lingmethodshub.github.io/content/R/lvc_r/114_lvcr.html}{Part
3}).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate the Variable Inflation Factor}
\FunctionTok{library}\NormalTok{(performance)}
\FunctionTok{check\_collinearity}\NormalTok{(td.glmer.parsimonious)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# Check for Multicollinearity

Low Correlation

       Term  VIF   VIF 95% CI Increased SE Tolerance Tolerance 95% CI
  After.New 2.68 [2.45, 2.94]         1.64      0.37     [0.34, 0.41]
 Morph.Type 2.06 [1.90, 2.25]         1.44      0.49     [0.44, 0.53]
     Before 4.93 [4.46, 5.46]         2.22      0.20     [0.18, 0.22]
     Stress 1.68 [1.56, 1.83]         1.30      0.59     [0.55, 0.64]
    Phoneme 1.87 [1.73, 2.04]         1.37      0.53     [0.49, 0.58]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate Condition Number}
\FunctionTok{library}\NormalTok{(JGmermod)}
\FunctionTok{collin.fnc.mer}\NormalTok{(td.glmer.parsimonious)}\SpecialCharTok{$}\NormalTok{cnumber}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 7.6
\end{verbatim}

The highest VIF is (still) lower than \(5\), indicating low collinearity
but \(\kappa = 7.6\), which is slightly above the threshold of \(6\)
indicating low-to-moderate collinearity. This latter value further
suggests investigating the across-parameter correlations (see
\href{https://lingmethodshub.github.io/content/R/lvc_r/114_lvcr.html}{Part
3}). For the moment, however, you will keep using the
\texttt{td.glmer.parsimonious} model.

You could choose to report the results of this treatment contrast
analysis in your manuscript. If you do, a \emph{Goldvarb}-style table
wouldn't be appropriate. Instead a \texttt{lme4}-style table is needed.

 \begin{table}[h]
\noindent
\begin{center}
\begin{threeparttable}
\caption{Mixed-effects logistic regression testing the fixed effect of \textsc{Following Context},  \textsc{Morpheme Type}, \textsc{Preceding Context}, \textsc{Stress} and \textsc{Phoneme} and a random intercept of \emph{Speaker} on the deletion of word-final \textipa{/t, d/} in Cape Breton English}

\begin{tabular}{lrrrcrc}
\toprule
\multicolumn{5}{l}{AIC = 1114, Marginal $R^2$ = .40, Conditional $R^2$ = .52}&\multicolumn{2}{c}{Observations}\\
\cmidrule(lr){6-7} 
Fixed Effects: & \multicolumn{1}{c}{Estimate} & \multicolumn{1}{c}{Std. Error}&\multicolumn{1}{c}{\textit{z}-value}&\multicolumn{1}{c}{\textit{p}-value} &\multicolumn{1}{c}{\textit{n}}&\multicolumn{1}{c}{\% Deletion} \\
\midrule
\textsc{Intercept} (all reference values) & 4.846 & 0.265 & 3.40 &$\ast$$\ast$$\ast$   &&\\
\textsc{Following Context} (vs. \textit{Consonant}) & &&& & 372 & 54\\
\quad\textit{Vowel} & -2.506&0.284&-8.82&$\ast$$\ast$$\ast$ & 259 & 28\\
\quad\textit{Pause} & -3.015&0.255&-11.82&$\ast$$\ast$$\ast$ & 558 & 20\\
\textsc{Morpheme Type} (vs. \textit{Semi-Weak Simple Past})&&&&&116&63\\
\quad\textit{Mono-morpheme} & 1.039&0.281&-3.70&$\ast$$\ast$$\ast$ & 762 & 37\\
\quad\textit{Weak Simple Past} & -3.358&0.396&-8.48&$\ast$$\ast$$\ast$ & 311 & 10\\
\textsc{Stress} (vs. \textit{Unstressed}) &&&  && 142 & 47\\
\quad\textit{Stressed} & -1.598&0.275&-5.81&$\ast$$\ast$$\ast$ & 1,047 & 31\\
\textsc{Preceding Context} (vs.\textit{\textipa{/s/}})&&&& &332 & 53\\
\quad\textit{Nasal} & -0.206&0.283&-0.73& & 209 & 39\\
\quad\textit{Other Fricative} & -0.614&0.377&-1.63&& 130 & 15\\
\quad\textit{Liquid} & -1.306  &0.317&-4.11&$\ast$$\ast$ & 269 & 42\\
\quad\textit{Stop} & -1.530&0.290&-5.27&$\ast$$\ast$$\ast$ & 249 & 27\\
\textsc{Phoneme} (vs. \textit{\textipa{/d/}})&&&&&878 &34\\
\quad\textit{\textipa{/t/}} &  -0.573&0.255&-2.25&$\ast$ & 311 & 29\\
\midrule
\multicolumn{5}{l}{Random Effects:} & \textit{sd} & \textit{n}\\
\midrule
\textsc{Speaker} &&&&& 0.892&  66\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \hfill$\ast\ast\ast$~$p<0.001$,  $\ast\ast$~$p<0.01$, $\ast$~$p<0.05$\\[-10pt]
\item  Treatment contrast coding. Estimate coefficients reported in log-odds. Total \textit{N} = 1,189. 
\item Model significantly better than null model (AIC = 1,456, $\chi^2$ = 362, df = 10, $\ast\ast\ast$)
\item Correlation of Fixed Effects $\le|0.61|$, $\kappa = 7.6$, Variable Inflation Factor $\le4.93$ 
\item Simultaneous test of the General Linear Hypothesis:
\item ~~~~~Mono-morpheme vs. Weak Simple Past = 0, Estimate: -2.319, Std. Error.: 0.296, \textit{z}-value: -7.84, $\ast\ast\ast$
\item ~~~~~Nasal vs. Liquid = 0, Estimate: 1.100, Std. Error: 0.276, \textit{z}-value: 3.99, $\ast\ast$
\item ~~~~~Nasal vs. Stop = 0, Estimate: -1.325, St. Error: 0.304, \textit{z}-value: -4.36, $\ast\ast\ast$
\item ~~~~All other contrasts non-significant
\end{tablenotes}
\end{threeparttable}
\end{center}
\end{table} 

The order of parameters in Table 1 is based on the the relative ordering
in of the
\href{https://lingmethodshub.github.io/content/R/lvc_r/112_lvcr.html}{Wald
\(\chi^2\) test}. The parameter levels are also ordered by their
estimates. You'll notice that all the estimates are negative and they
don't match up to the results reported in the \texttt{glmer()} results
above. This is because, before creating this table, each factor was
reordered based on level estimates so that the reference level, i.e.,
first level, was also the level that most favoured the application
value. This step is not needed, but I find this makes understanding the
constraint hierarchy much easier for the reader. It also means that the
intercept represents the likelihood of the application value when it is
most likely. Alternatively, you could re-arrange the factor levels so
that the least likely levels were the reference levels. This would
result in estimates that were all positive and showed how much switching
levels improved the likelihood. What you choose to do is entirely up to
you and the story you want to tell with your analysis.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Reorder levels of Before from most favouring to}
\CommentTok{\# least favouring}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Before }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Before, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"S"}\NormalTok{, }\StringTok{"Nasal"}\NormalTok{,}
    \StringTok{"Other Fricative"}\NormalTok{, }\StringTok{"Liquid"}\NormalTok{, }\StringTok{"Stop"}\NormalTok{))}
\CommentTok{\# Reorder levels of After.New from most favouring}
\CommentTok{\# to least favouring}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{After.New }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{After.New, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Consonant"}\NormalTok{,}
    \StringTok{"Vowel"}\NormalTok{, }\StringTok{"Pause"}\NormalTok{))}
\CommentTok{\# Reorder levels of Morph.Type from most}
\CommentTok{\# favouring to least favouring}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Morph.Type }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Morph.Type, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Semi{-}Weak"}\NormalTok{,}
    \StringTok{"Mono"}\NormalTok{, }\StringTok{"Past"}\NormalTok{))}
\CommentTok{\# Reorder levels of Stress from most favouring to}
\CommentTok{\# least favouring}
\NormalTok{td}\SpecialCharTok{$}\NormalTok{Stress }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(td}\SpecialCharTok{$}\NormalTok{Stress, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Unstressed"}\NormalTok{,}
    \StringTok{"Stressed"}\NormalTok{))}
\CommentTok{\# Most Parsimonious Model: Generalized linear}
\CommentTok{\# mixed effects model with the fixed main effects}
\CommentTok{\# of Before, After.New, Morph.Type, Stress,}
\CommentTok{\# Phoneme, , and the random effect of Speaker}
\NormalTok{td.glmer }\OtherTok{\textless{}{-}} \FunctionTok{glmer}\NormalTok{(Dep.Var }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Before }\SpecialCharTok{+}\NormalTok{ After.New }\SpecialCharTok{+}\NormalTok{ Morph.Type }\SpecialCharTok{+}
\NormalTok{    Stress }\SpecialCharTok{+}\NormalTok{ Phoneme }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ Speaker), }\AttributeTok{data =}\NormalTok{ td, }\AttributeTok{family =} \StringTok{"binomial"}\NormalTok{,}
    \AttributeTok{control =} \FunctionTok{glmerControl}\NormalTok{(}\AttributeTok{optCtrl =} \FunctionTok{list}\NormalTok{(}\AttributeTok{maxfun =} \DecValTok{20000}\NormalTok{),}
        \AttributeTok{optimizer =} \StringTok{"bobyqa"}\NormalTok{))}
\FunctionTok{summary}\NormalTok{(td.glmer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: binomial  ( logit )
Formula: Dep.Var ~ Before + After.New + Morph.Type + Stress + Phoneme +  
    (1 | Speaker)
   Data: td
Control: glmerControl(optCtrl = list(maxfun = 20000), optimizer = "bobyqa")

     AIC      BIC   logLik deviance df.resid 
    1114     1175     -545     1090     1177 

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-5.223 -0.488 -0.259  0.495 14.033 

Random effects:
 Groups  Name        Variance Std.Dev.
 Speaker (Intercept) 0.796    0.892   
Number of obs: 1189, groups:  Speaker, 66

Fixed effects:
                      Estimate Std. Error z value Pr(>|z|)    
(Intercept)              4.846      0.635    7.63  2.4e-14 ***
BeforeNasal             -0.206      0.283   -0.73  0.46716    
BeforeOther Fricative   -0.614      0.377   -1.63  0.10350    
BeforeLiquid            -1.306      0.317   -4.11  3.9e-05 ***
BeforeStop              -1.530      0.290   -5.27  1.4e-07 ***
After.NewVowel          -2.506      0.284   -8.82  < 2e-16 ***
After.NewPause          -3.015      0.255  -11.82  < 2e-16 ***
Morph.TypeMono          -1.039      0.281   -3.70  0.00022 ***
Morph.TypePast          -3.358      0.396   -8.48  < 2e-16 ***
StressStressed          -1.598      0.275   -5.81  6.2e-09 ***
Phonemet                -0.573      0.255   -2.25  0.02461 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) BfrNsl BfrOtF BfrLqd BfrStp Aft.NV Aft.NP Mrp.TM Mrp.TP
BeforeNasal -0.536                                                        
BfrOthrFrct -0.222  0.264                                                 
BeforeLiqud -0.705  0.583  0.323                                          
BeforeStop  -0.458  0.439  0.395  0.519                                   
After.NwVwl -0.388 -0.033  0.067  0.132  0.184                            
After.NewPs -0.514  0.172  0.184  0.451  0.510  0.529                     
Morph.TypMn -0.573  0.162  0.027  0.337 -0.032 -0.050 -0.009              
Mrph.TypPst -0.513  0.166 -0.318  0.315 -0.041  0.106  0.188  0.666       
StrssStrssd -0.604  0.253  0.056  0.185  0.294  0.511  0.230  0.123  0.122
Phonemet    -0.660  0.473  0.111  0.608  0.162  0.009  0.265  0.337  0.333
            StrssS
BeforeNasal       
BfrOthrFrct       
BeforeLiqud       
BeforeStop        
After.NwVwl       
After.NewPs       
Morph.TypMn       
Mrph.TypPst       
StrssStrssd       
Phonemet     0.106
\end{verbatim}

By reordering the levels of you verify some intuitions generated by
\href{https://lingmethodshub.github.io/content/R/lvc_r/114_lvcr.html}{previous
analyses} about the constraint hierarchy for \texttt{Before}. There is
not a significant difference between the reference level (\texttt{S})
and \texttt{Nasal} or between the reference level (\texttt{S}) and
\texttt{Other\ Fricatives}. This suggests that your constraint hierarchy
is actually \texttt{All\ Fricatives/Nasals} \textgreater{}
\texttt{Liquids/Stops} (remember in the non-reordered
\texttt{summary(td.glmer)} \texttt{Liquids} and \texttt{Stops} were not
significantly different). This is an insight into the data that the
\texttt{glmer()} model with sum contrasts couldn't have provided.

But what about the other parameter levels? For example, there is a
significant difference between following consonant and following vowel.
There is also a significant difference between following consonant and
following pause. But is there a significant difference between following
vowel and following pause? You could run a series of \texttt{glmer()}
models in which you keep reordering the parameter levels to find out
where the significant differences are. However, the \texttt{glmer()}
model you've just constructed contains this information, you just need
to know how to ask for it.

The first task is to create a contrast matrix of all the comparisons you
want to make. You use \texttt{rbind()} to create two rows (which you
call \texttt{"After.NewVowel\ vs.\ After.NewPause"} and
\texttt{"Morph.TypeMono\ vs.\ Morph.TypePast"}). Each row has 11 cells.
These 11 cells correspond to the 11 rows in the \texttt{glmer()} fixed
effects results: the first cell corresponds to the \texttt{(Intercept)},
the second cell corresponds to \texttt{BeforeNasal}, etc. To compare two
estimates place a \texttt{1} and \texttt{-1} in the corresponding cells
and a \texttt{0} in all remaining cells. In the code below there is a
\texttt{1} in the sixth and a \texttt{-1} in the seventh cells because
\texttt{After.NewVowel} and \texttt{After.NewPause} are the sixth and
seventh rows in the fixed effects results. You use the \texttt{glht()}
function (a simultaneous test of the General Linear Hypotheses) in the
\texttt{multcomp} package to calculate the comparisons. A
\texttt{summary()} for that function displays the results.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create contrast matrix}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{After.NewVowel vs. After.NewPause}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}
    \DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{), }\StringTok{\textasciigrave{}}\AttributeTok{Morph.TypeMono vs. Morph.TypePast}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}
    \DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\CommentTok{\# Test pairwise comparisons}
\FunctionTok{library}\NormalTok{(multcomp)}
\FunctionTok{summary}\NormalTok{(}\FunctionTok{glht}\NormalTok{(td.glmer, d))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

     Simultaneous Tests for General Linear Hypotheses

Fit: glmer(formula = Dep.Var ~ Before + After.New + Morph.Type + Stress + 
    Phoneme + (1 | Speaker), data = td, family = "binomial", 
    control = glmerControl(optCtrl = list(maxfun = 20000), optimizer = "bobyqa"))

Linear Hypotheses:
                                       Estimate Std. Error z value Pr(>|z|)    
After.NewVowel vs. After.NewPause == 0    0.509      0.263    1.94      0.1    
Morph.TypeMono vs. Morph.TypePast == 0    2.319      0.296    7.84   <1e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)
\end{verbatim}

The results indicate that the difference in likelihood of
\texttt{After.NewVowel} and \texttt{After.NewPause} on the
\texttt{Intercept} are not significantly different from zero
(\(p>0.05\)). This means that the real contrast for this factor group is
consonant versus not-consonant. On the other hand, there is a
significant difference between \texttt{Morph.TypeMono} and
\texttt{Morph.TypePast} indicating that this factor group has a real
three-way contrast between semi-weak simple past, mono-morphemes, and
weak simple past. Again, by performing a detailed analysis of the
contrasts between factors \textbf{in addition to} an analysis of the
contrasts between factors and their mean, you achieve a much more
nuanced (and I argue superior) understanding of the three lines of
evidence because you can pinpoint exactly where significant contrasts
exist.

An easier method for generating the contrast matrix is provided below.
For a different analysis replace \texttt{td.glmer.parsimonious} with
your model name, and replace \texttt{Before}, \texttt{After.New}, etc.
with your own predictors. You don't need to include all predictors. You
could also include more. Just adjust the number of \texttt{k1},
\texttt{k2}, etc. objects you create. This method provides all the
contrasts for a single predictor variable, unlike the method above, in
which you specify the specific contrasts you are interested in. I have
not included \texttt{Phoneme} or \texttt{Stress} here as they are
binary, so the contrast between the two levels is represented in the
\texttt{summary(td.glmer.parsimonious)} output already.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(multcomp)}
\NormalTok{k1 }\OtherTok{\textless{}{-}} \FunctionTok{glht}\NormalTok{(td.glmer.parsimonious, }\FunctionTok{mcp}\NormalTok{(}\AttributeTok{Before =} \StringTok{"Tukey"}\NormalTok{))}\SpecialCharTok{$}\NormalTok{linfct}
\NormalTok{k2 }\OtherTok{\textless{}{-}} \FunctionTok{glht}\NormalTok{(td.glmer.parsimonious, }\FunctionTok{mcp}\NormalTok{(}\AttributeTok{After.New =} \StringTok{"Tukey"}\NormalTok{))}\SpecialCharTok{$}\NormalTok{linfct}
\NormalTok{k3 }\OtherTok{\textless{}{-}} \FunctionTok{glht}\NormalTok{(td.glmer.parsimonious, }\FunctionTok{mcp}\NormalTok{(}\AttributeTok{Morph.Type =} \StringTok{"Tukey"}\NormalTok{))}\SpecialCharTok{$}\NormalTok{linfct}

\FunctionTok{summary}\NormalTok{(}\FunctionTok{glht}\NormalTok{(td.glmer.parsimonious, }\AttributeTok{linfct =} \FunctionTok{rbind}\NormalTok{(k1,}
\NormalTok{    k2, k3)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

     Simultaneous Tests for General Linear Hypotheses

Fit: glmer(formula = Dep.Var ~ After.New + Morph.Type + Before + Stress + 
    Phoneme + (1 | Speaker), data = td, family = "binomial", 
    control = glmerControl(optCtrl = list(maxfun = 20000), optimizer = "bobyqa"))

Linear Hypotheses:
                              Estimate Std. Error z value Pr(>|z|)    
Nasal - Liquid == 0              1.100      0.276    3.99   <0.001 ***
Other Fricative - Liquid == 0    0.692      0.407    1.70   0.6009    
S - Liquid == 0                  1.306      0.317    4.11   <0.001 ***
Stop - Liquid == 0              -0.224      0.299   -0.75   0.9938    
Other Fricative - Nasal == 0    -0.408      0.408   -1.00   0.9630    
S - Nasal == 0                   0.206      0.283    0.73   0.9950    
Stop - Nasal == 0               -1.325      0.304   -4.36   <0.001 ***
S - Other Fricative == 0         0.614      0.377    1.63   0.6531    
Stop - Other Fricative == 0     -0.916      0.374   -2.45   0.1571    
Stop - S == 0                   -1.530      0.290   -5.27   <0.001 ***
Pause - Consonant == 0          -3.015      0.255  -11.82   <0.001 ***
Vowel - Consonant == 0          -2.506      0.284   -8.82   <0.001 ***
Vowel - Pause == 0               0.509      0.263    1.94   0.4305    
Past - Mono == 0                -2.319      0.296   -7.84   <0.001 ***
Semi-Weak - Mono == 0            1.039      0.281    3.70   0.0031 ** 
Semi-Weak - Past == 0            3.358      0.396    8.48   <0.001 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)
\end{verbatim}

You can add the results from this \texttt{glht()} test to your
manuscript table, as in Table 1.

\hypertarget{visualizing-the-fixed-effects}{%
\subsection{Visualizing the fixed
effects}\label{visualizing-the-fixed-effects}}

As in
\href{https://lingmethodshub.github.io/content/R/lvc_r/112_lvcr.html}{Part
2}, you can use the \texttt{plot\_model()} function to examine the fixed
effects.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required packages}
\FunctionTok{library}\NormalTok{(sjPlot)}
\FunctionTok{library}\NormalTok{(sjlabelled)}
\FunctionTok{library}\NormalTok{(sjmisc)}
\FunctionTok{library}\NormalTok{(ggplot2)}


\CommentTok{\# Plot fixed effects}
\FunctionTok{plot\_model}\NormalTok{(td.glmer, }\AttributeTok{transform =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{show.values =} \ConstantTok{TRUE}\NormalTok{,}
    \AttributeTok{value.offset =} \FloatTok{0.3}\NormalTok{, }\AttributeTok{vline.color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Likelihood of (t,d) deletion"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{116_lvcr_files/figure-pdf/unnamed-chunk-9-1.pdf}

}

\end{figure}

Unlike the fixed effects plot for the sum contrast coding model, in
which zero on the \emph{x}-axis represented the grand mean, or overall
baseline likelihood, zero on the \emph{x}-axis here represents the
likelihood when all predictors are set to their reference values. You
have arbitrarily set all the reference values to the most favouring
values, so all the values represented in the plot are below zero, as
they have negative estimates (they all disfavour \texttt{Deletion}
relative to the reference values).

Any predictor level whose error bars overlap the zero line are not
significantly different from the reference level of that predictor. As
is shown in the \texttt{glmer()} output, for preceding context,
\texttt{Nasal} and \texttt{Other\ Fricative} are not significantly
different from the reference value \texttt{S}. The error bars can also
tell you how the non-reference values relate to each other, as with the
\texttt{glht()} test. Any error bars for levels of the same predictor
that overlap indicate those levesl are not significantly different from
each other. By looking at the plot you can see that for preceding
context \texttt{Nasal} and \texttt{Stop} and \texttt{Nasal} and
\texttt{Liquid} do not overlap (though the space between \texttt{Nasal}
and \texttt{Liquid} is quite hard to see), but all other non-reference
values do. Likewise, for following context \texttt{Vowel} and
\texttt{Pause} overlap, indicating that they are not significantly
differnet from each other, despite both being significantly different
from the reference level \texttt{Consonant}. For morpheme type, however,
both \texttt{Mono} and \texttt{Past} are significantly different from
the reference value \texttt{Semi-Weak} as their error bars do not cross
the zero line, and also significantly different from each other, as
their error bars do not overlap.

Instead of colouring all the predictor levels similarly (as they are all
below zero), you can instead colour them by predictor type using the
\texttt{group.terms=} option, and then specifying which group each term
belongs to, as in the example below. The first four terms (the four
\texttt{Before} levels) are all \texttt{1}, the next two (the two
\texttt{After.New} levels) are \texttt{2}, etc. This might make
presenting a plot like this easier to read, especially as part of a
slide presentation.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot fixed effects}
\FunctionTok{plot\_model}\NormalTok{(td.glmer, }\AttributeTok{transform =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{show.values =} \ConstantTok{TRUE}\NormalTok{,}
    \AttributeTok{value.offset =} \FloatTok{0.3}\NormalTok{, }\AttributeTok{vline.color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Likelihood of (t,d) deletion"}\NormalTok{,}
    \AttributeTok{group.terms =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{116_lvcr_files/figure-pdf/unnamed-chunk-10-1.pdf}

}

\end{figure}



\end{document}
