project:
  title: "LVC_R"
  render:
    - "!renv/"

doi: "10.5281/zenodo.7160718"  
editor: source

citation:
  volume: "Doing LVC with R"
  volume-title: "Doing LVC with R"
  author: "Matt Hunt Gardner"
